### ISSUE TITLE
Build issues on arm64

### ISSUE THREAD

**Issue by intelliant01** [Sunbird-Ed/sunbird-desktop-app#138]
When trying to build on a Raspberry Pi 4B using the included build.sh got the below issue. But I think this issue will be visible on any platform -
```
sunbird-desktop-app$ ./build.sh
npm WARN tarball tarball data for ansi-wrap@0.1.0 (sha1-qCJQ3bABXponyoLoLqYDu/pF768=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for semver@6.3.0 (sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for grunt@1.0.4 (sha512-PYsMOrOC+MsdGEkFVwMaMyc6Ob7pKmq+deg1Sjr+vvMWp35sztfwKE7qoN51V+UEtHsyNuMcGdgMLFkBHvMxHQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for meow@5.0.0 (sha512-CbTqYU17ABaLefO8vCU153ZZlprKYWDljcndKKDCFcYQITzWCXZAVk4QMFZPgvzrnUQ3uItnIE/LoUOwrT15Ig==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @project-sunbird/ext-framework-server@0.1.26 (sha512-lHDx0mrYURKXyvSbBCgpBuPao0YECUAK41LWbdz4MnnIZmkEdaAPhFBfwdKFwLwG7/TsDi/UxZZSbOXQs9vb6Q==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for xml2js@0.4.23 (sha512-ySPiMjM0+pLDftHgXY4By0uswI3SPKLDw/i3UXbnO8M/p28zqexCUoPmQFrYD+/1BzhGJSs2i1ERWKJAtiLrug==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for p-limit@2.2.1 (sha512-85Tk+90UCVWvbDavCLKPOLC9vvY8OwEX/RtKF+/1OADJMVlFfEHOiMTPVyxg7mk/dKa+ipdHm0OUkTvCpMTuwg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for electron-builder@21.2.0 (sha512-x8EXrqFbAb2L3N22YlGar3dGh8vwptbB3ovo3OF6K7NTpcsmM2zEoJv7GhFyX73rNzSG2HaWpXwGAtOp2JWiEw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for is-arrayish@0.3.2 (sha512-eVRqCvVlZbuw3GrM63ovNSNAeA1K16kaR/LRY/92w0zxQ5/1YzwblUX652i4Xs9RwAGjW9d9y6X88t8OaAJfWQ==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for reflect-metadata@0.1.13 (sha512-Ts1Y/anZELhSsjMcU605fU9RE4Oi3p5ORujwbIKXfWa+0Zxs510Qrmrce5/Jowq3cHSZSJqBjypxmHarc+vEWg==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for useragent@2.3.0 (sha512-4AoH4pxuSvHCjqLO04sU6U/uE65BYza8l/KKBS0b0hnUPWi+cQ2BpeTEwejCSx9SPV5/U03nniDTrWx5NrmKdw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for uglify-js@3.7.2 (sha512-uhRwZcANNWVLrxLfNFEdltoPNhECUR3lc+UdJoG9CBpMcSnKyWA94tc3eAujB1GcMY5Uwq8ZMp4qWpxWYDQmaA==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for object-keys@1.1.1 (sha512-NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for engine.io-client@3.2.1 (sha512-y5AbkytWeM4jQr7m/koQLc5AxpRKC1hEVUb/s1FUAWEJq5AzJJ4NLvzuKPuxtDi5Mq755WuDvZ6Iv2rXj4PTzw==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for dmg-builder@21.2.0 (sha512-9cJEclnGy7EyKFCoHDYDf54pub/t92CQapyiUxU0w9Bj2vUvfoDagP1PMiX4XD5rPp96141h9A+QN0OB4VgvQg==) seems to be corrupted. Trying one more time.

> phantomjs-prebuilt@2.1.16 install /home/mssadmin/develop/sunbird-desktop-app/src/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN sunbird@1.2.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mssadmin/.npm/_logs/2020-09-30T11_17_06_024Z-debug.log

> sunbird@1.2.0 build /home/mssadmin/develop/sunbird-desktop-app/src
> gulp build

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mssadmin/develop/sunbird-desktop-app/src/node_modules/nodegit/dist/nodegit.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunbird@1.2.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunbird@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mssadmin/.npm/_logs/2020-09-30T11_17_10_882Z-debug.log
./build.sh: line 8: cd: client: No such file or directory

> phantomjs-prebuilt@2.1.16 install /home/mssadmin/develop/sunbird-desktop-app/src/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN electron-builder-squirrel-windows@22.2.0 requires a peer of app-builder-lib@~22.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN sunbird@1.2.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mssadmin/.npm/_logs/2020-09-30T11_17_46_614Z-debug.log
npm ERR! missing script: offline-prod

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mssadmin/.npm/_logs/2020-09-30T11_17_48_708Z-debug.log
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/mssadmin/develop/sunbird-desktop-app/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/mssadmin/develop/sunbird-desktop-app/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mssadmin/.npm/_logs/2020-09-30T11_17_50_717Z-debug.log
tar: src: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

```

**Comment by intelliant01** [comment]
Seems that the dependency on the deprecated `phantomjs-prebuilt` is one of the issues.

**Comment by cyberorg** [comment]
apt install phantomjs to fix the above issue, however you will run into few more issues for example:

1. Moment - Module not found: Error: Can't resolve './locale' (temp fix, ln -s ../locale in path mentioned in error)
2. amd64 fpm in electron-builder, so have to use system fpm
3. deb not install-able due to wrong compression https://github.com/jordansissel/fpm/pull/1611
